spring:
  application:
    name: Chatbot
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat-bot}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: UTC
app:
  security:
    access_secret: ${JWT_ACCESS_SECRET:VERYSECRETPOXXUYBESTSECRETEVERKNOWN2HUMANITY333}
    refresh_secret: ${JWT_REFRESH_SECRET:VERYSECRETPOXXUYBESTSECRETEVERKNOWN2HUMANITY333SECRET}
    access_expiration: 3600 #seconds
    refresh_expiration: 2592000 #seconds
langchain4j:
  open-ai:
    #    chat-model:
    streaming-chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o
      log-requests: true
      log-responses: true