spring:
  application:
    name: Chatbot
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5434}/${POSTGRES_DB:chat-bot}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    time-zone: Europe/Warsaw
  config:
    import: file:./local/.env[.properties]
app:
  security:
    access-secret: ${JWT_ACCESS_SECRET:VERYSECRETPOXXUYBESTSECRETEVERKNOWN2HUMANITY333}
    refresh-secret: ${JWT_REFRESH_SECRET:VERYSECRETPOXXUYBESTSECRETEVERKNOWN2HUMANITY333SECRET}
    access-expiration: 3600 #seconds
    refresh-expiration: 2592000 #seconds
langchain4j:
  open-ai:
    chat-model:
#    streaming-chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o
      log-requests: true
      log-responses: true
      max-tokens: 100