spring:
  application:
    name: Chatbot
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat-bot}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: UTC
app:
  security:
    secret: ${JWT_SECRET:VERYSECRETPOXXUYBESTSECRETEVERKNOWN2HUMANITY333}
    expiration: 3600