services:
  postgres:
    image: postgres:latest
    container_name: chat-bot
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chat-bot
      DATASOURCE_URL: ${DATASOURCE_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_ACCESS_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
